---
language: python
python: "2.7"

env:
  - SITE=test-simple-playbook.yml

before_install:
  - sudo apt-get -y -qq update
  - sudo apt-get -y -qq install aptitude

install:
  # Install Ansible. The other packages are to allow SNI veriification of SSL certs.
  - yes | pip install ansible urllib3 pyopenssl ndg-httpsclient pyasn1

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/$SITE --syntax-check

  # Run the role/playbook with ansible-playbook.
  - script -q -c "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo" output.txt

  - >
    grep -q 'failed=0' output.txt
    && (echo 'Role run: pass' && exit 0) 
    || (echo 'Role run: fail' && exit 1)

  # Make sure GitLab is running.
  - >
    curl --insecure -s -o /dev/null -w "%{http_code}" http://localhost:631
    | grep -q '200'
    && (echo 'Status code 200 test: pass' && exit 0)
    || (echo 'Status code 200 test: fail' && exit 1)